'use client';
import {useState} from 'react';
import {Box,Check,RotateCcw,Play,Plus,Move,ArrowRight} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Tabs,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {assemblySteps,palette} from '@/lib/artas/catalog';
import ProductScene from './ProductScene';
export default function AssemblyGame(){const [kind,setKind]=useState<'roller'|'gate'>('roller');const [stage,setStage]=useState(0);const [selected,setSelected]=useState('');const [mistakes,setMistakes]=useState(0);const [message,setMessage]=useState('Wybierz element i zamontuj go w modelu. Zacznij od prowadnic.');const [test,setTest]=useState(false);const steps=assemblySteps[kind];const done=stage===steps.length;const reset=(k:'roller'|'gate'=kind)=>{setKind(k);setStage(0);setSelected('');setMistakes(0);setTest(false);setMessage('Wybierz element i zamontuj go w modelu. Zacznij od prowadnic.')};const choose=(id:string)=>{if(steps.findIndex(s=>s.id===id)>=stage){setSelected(id);setMessage('Wybrano: '+(steps.find(s=>s.id===id)?.name??id)+'. Naciśnij „Zamontuj element” lub przeciągnij go do modelu.')}};const mount=(id=selected)=>{if(!id||done)return;const actual=steps.findIndex(s=>s.id===id);if(actual<stage){setMessage('Ten element jest już na miejscu.');return}if(id!==steps[stage].id){setMistakes(m=>m+1);setMessage('Jeszcze nie. Najpierw: '+steps[stage].name.toLowerCase()+'. '+steps[stage].hint);return}setStage(s=>s+1);setSelected('');setMessage(stage===5?'Gotowe! Uruchom test i zobacz swoją konstrukcję w ruchu.':steps[stage].hint+' Następnie: '+steps[stage+1].name.toLowerCase()+'.')};
 return <div className="game-shell assembly"><div className="game-console"><div className="console-label"><Box size={16}/> ARTAS BUILD <span>WARSZTAT 3D</span></div><div className="game-stats"><span><b>{stage}/6</b> elementów</span><span><b>{mistakes}</b> pomyłek</span></div></div><div className="assembly-grid"><div className="assembly-view" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const id=e.dataTransfer.getData('text/plain');mount(id)}}><div className="scene-meta"><span>{done?'KONSTRUKCJA GOTOWA':'MONTAŻ W TOKU'}</span><span>Obróć model <Move size={13}/></span></div><ProductScene kind={kind} color={palette[0].hex} profile={kind==='gate'?500:39} open={test?100:0} assembled={stage} selected={selected} onPick={choose} zoom={1}/><div className="assembly-step-badge">{done?<Check size={16}/>:<Plus size={16}/>} {done?'6 / 6 — Dobra robota':`Krok ${stage+1} — ${steps[stage].name}`}</div></div><div className="assembly-parts"><Tabs value={kind} onValueChange={v=>reset(v as 'roller'|'gate')}><TabsList className="artas-tabs"><TabsTrigger value="roller">Roleta</TabsTrigger><TabsTrigger value="gate">Brama</TabsTrigger></TabsList></Tabs><p className="small-label">TWOJE PODZESPOŁY</p><div className="parts-list">{[2,0,4,1,5,3].map(i=>{const p=steps[i];return <button key={p.id} className={i<stage?'mounted':selected===p.id?'part-selected':''} disabled={i<stage} draggable={i>=stage} onDragStart={e=>{e.dataTransfer.setData('text/plain',p.id);choose(p.id)}} onClick={()=>choose(p.id)}>{i<stage?<Check size={17}/>:<Box size={17}/>}<span>{p.name}</span>{selected===p.id&&<ArrowRight size={14}/>}</button>})}</div>{done?<button className="primary-btn" onClick={()=>setTest(!test)}>{test?'Zamknij konstrukcję':'Uruchom test'}<Play size={16}/></button>:<button disabled={!selected} className="primary-btn" onClick={()=>mount()}>Zamontuj element <Plus size={16}/></button>}<button className="text-button" onClick={()=>reset()}><RotateCcw size={14}/> Zacznij od nowa</button></div></div><div className="game-bottom"><Progress value={stage/6*100} aria-label="Postęp składania"/><p className="game-message" role="status">{message}</p><small className="technical-note">Uproszczona kolejność dydaktyczna. Rzeczywisty montaż, regulację sprężyn i odbiór zabezpieczeń wykonuje fachowiec według instrukcji danego systemu.</small></div></div>
}
