'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ChevronsDown} from 'lucide-react';
import {gatePath,splitPanels} from '@/lib/artas/mechanics';

const HERO_GATE_HEIGHT=4.5;
const HERO_PANEL_HEIGHT=.5;
const HERO_PANEL_WIDTH=20;
const HERO_CAMERA_EXTENT=2.35;

export default function Opening(){
 const runway=useRef<HTMLElement>(null);const canvasHost=useRef<HTMLDivElement>(null);const progress=useRef(0);const [amount,setAmount]=useState(0);const [reduced,setReduced]=useState(false);
 useEffect(()=>{const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');const updateMotion=()=>setReduced(motionQuery.matches);updateMotion();motionQuery.addEventListener('change',updateMotion);const handleScroll=()=>{if(!runway.current)return;const rect=runway.current.getBoundingClientRect();const travel=window.innerHeight*1.4/.7;const nextAmount=Math.min(1,Math.max(0,((window.innerWidth<=760?72:86)-rect.top)/travel));progress.current=nextAmount;setAmount(nextAmount)};addEventListener('scroll',handleScroll,{passive:true});addEventListener('resize',handleScroll);handleScroll();return()=>{removeEventListener('scroll',handleScroll);removeEventListener('resize',handleScroll);motionQuery.removeEventListener('change',updateMotion)}},[]);
 useEffect(()=>{if(reduced)return;let disposed=false;let cleanup=()=>{};(async()=>{const THREE=await import('three');if(disposed||!canvasHost.current)return;const element=canvasHost.current;let renderer:import('three').WebGLRenderer;try{renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'low-power',alpha:true})}catch{return}renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));renderer.setClearColor(0,0);element.appendChild(renderer.domElement);
  const scene=new THREE.Scene();const camera=new THREE.OrthographicCamera(-3,3,2,-2,.1,30);camera.position.set(0,0,8);camera.lookAt(0,0,0);
  const panelMaterial=new THREE.MeshStandardMaterial({color:'#777a78',metalness:.68,roughness:.32});const seamMaterial=new THREE.MeshStandardMaterial({color:'#24282b',metalness:.45,roughness:.48});const guideMaterial=new THREE.MeshStandardMaterial({color:'#a9b0b5',metalness:.8,roughness:.25});const panelRoot=new THREE.Group();scene.add(panelRoot);const panels:{group:import('three').Group;baseY:number}[]=[];const geometries:import('three').BufferGeometry[]=[];const materials=[panelMaterial,seamMaterial,guideMaterial];let panelBase=0;
  for(const panelHeight of splitPanels(HERO_GATE_HEIGHT,HERO_PANEL_HEIGHT)){const panelGroup=new THREE.Group();const panelGeometry=new THREE.BoxGeometry(HERO_PANEL_WIDTH,Math.max(panelHeight-.018,.08),.10);const panelMesh=new THREE.Mesh(panelGeometry,panelMaterial);panelGroup.add(panelMesh);const seamGeometry=new THREE.BoxGeometry(HERO_PANEL_WIDTH,.018,.115);const seamMesh=new THREE.Mesh(seamGeometry,seamMaterial);seamMesh.position.y=-panelHeight/2+.009;panelGroup.add(seamMesh);panelRoot.add(panelGroup);geometries.push(panelGeometry,seamGeometry);panels.push({group:panelGroup,baseY:panelBase+panelHeight/2});panelBase+=panelHeight}
  const guideGroup=new THREE.Group();scene.add(guideGroup);const guideStart=HERO_GATE_HEIGHT-.32;for(const trackX of [-2.75,2.75]){const points:import('three').Vector3[]=[];for(let pointIndex=0;pointIndex<=16;pointIndex++){const distance=guideStart+pointIndex/16*.32*Math.PI/2;const path=gatePath(distance,HERO_GATE_HEIGHT);points.push(new THREE.Vector3(trackX,path.y-HERO_GATE_HEIGHT/2,path.z))}const guideCurve=new THREE.CatmullRomCurve3(points);const guideGeometry=new THREE.TubeGeometry(guideCurve,32,.018,6,false);guideGroup.add(new THREE.Mesh(guideGeometry,guideMaterial));geometries.push(guideGeometry)}const topGuideGeometry=new THREE.BoxGeometry(5.65,.035,.065);const topGuide=new THREE.Mesh(topGuideGeometry,guideMaterial);topGuide.position.set(0,HERO_GATE_HEIGHT/2-.025,-.64);guideGroup.add(topGuide);geometries.push(topGuideGeometry);
  scene.add(new THREE.HemisphereLight('#d8e1e2','#080a0b',2));const keyLight=new THREE.PointLight('#fff5e5',32,20);keyLight.position.set(-1,2,3);scene.add(keyLight);const sideLight=new THREE.PointLight('#738f9f',16,15);sideLight.position.set(4,0,2);scene.add(sideLight);
  const resize=()=>{const width=element.clientWidth;const height=element.clientHeight;if(!width||!height)return;renderer.setSize(width,height,false);camera.left=-HERO_CAMERA_EXTENT*width/height;camera.right=HERO_CAMERA_EXTENT*width/height;camera.top=HERO_CAMERA_EXTENT;camera.bottom=-HERO_CAMERA_EXTENT;camera.updateProjectionMatrix()};const resizeObserver=new ResizeObserver(resize);resizeObserver.observe(element);resize();let frame=0;let renderedProgress=-1;const draw=()=>{frame=requestAnimationFrame(draw);if(document.hidden)return;const currentProgress=progress.current;if(Math.abs(renderedProgress-currentProgress)<.0001)return;renderedProgress=currentProgress;const lift=currentProgress*HERO_GATE_HEIGHT;for(const panel of panels){const path=gatePath(panel.baseY+lift,HERO_GATE_HEIGHT);panel.group.position.set(0,path.y-HERO_GATE_HEIGHT/2,path.z);panel.group.rotation.x=path.angle}renderer.render(scene,camera)};draw();cleanup=()=>{cancelAnimationFrame(frame);resizeObserver.disconnect();for(const geometry of geometries)geometry.dispose();for(const material of materials)material.dispose();renderer.dispose();renderer.domElement.remove()}})();return()=>{disposed=true;cleanup()}},[reduced]);
 const skip=()=>{if(runway.current){const y=runway.current.offsetTop+window.innerHeight*1.4/.7-(window.innerWidth<=760?72:86);window.scrollTo({top:y,behavior:reduced?'instant':'smooth'})}};
 return <section ref={runway} className={'intro-runway '+(reduced?'motion-reduced':'')} aria-label="Otwórz stronę rozwijaniem"><div className="intro-sticky"><section className="hero"><img className="hero-image" src="/images/original-16.jpeg" alt="Nowoczesny dom z roletami i bramą garażową" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">ARTAS / ARCHITEKTURA KOMFORTU</p><h1>Świat na zewnątrz.<br/>Spokój <em>wewnątrz.</em></h1><p>Rolety, bramy i pergole. Dopasowane do Twojego domu, zaprojektowane do Twojego życia.</p><a className="primary-btn" href="#oferta">Odkryj możliwości <ArrowDown size={18}/></a></div><div className="hero-bottom"><span>TWÓJ DOM. TWÓJ RYTM.</span><span>PRECYZJA, KTÓRĄ CZUĆ.</span></div></section>{!reduced&&<div className="opening-curtain" style={{pointerEvents:amount>.985?'none':'auto',visibility:amount>.995?'hidden':'visible'}}><div className="curtain-fallback" style={{transform:`translateY(${-amount*115}%)`}}/><div ref={canvasHost} className="curtain-canvas"/><div className="curtain-message" style={{transform:`translateY(${-amount*110}vh)`,opacity:Math.max(0,1-amount*2)}}><p className="eyebrow">KAŻDY DOBRY DZIEŃ ZACZYNA SIĘ OD OTWARCIA</p><div className="opening-title">Otwórz się<br/>na <em>więcej.</em></div><p>Rozwijaj. To Ty masz kontrolę.</p><ChevronsDown size={25}/></div><div className="opening-bottom"><button onClick={skip}>Pomiń otwarcie <ArrowDown size={14}/></button><span>OTWARCIE <strong>{Math.round(amount*100).toString().padStart(2,'0')}%</strong></span><div className="opening-progress" style={{width:`${amount*100}%`}}/></div></div>}</div></section>
}
