'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowDown,ChevronsDown} from 'lucide-react';
export default function Opening(){
 const runway=useRef<HTMLElement>(null);const canvasHost=useRef<HTMLDivElement>(null);const progress=useRef(0);const [amount,setAmount]=useState(0);const [reduced,setReduced]=useState(false);
 useEffect(()=>{const mq=matchMedia('(prefers-reduced-motion: reduce)');const updateMotion=()=>setReduced(mq.matches);updateMotion();mq.addEventListener('change',updateMotion);const scroll=()=>{if(!runway.current)return;const rect=runway.current.getBoundingClientRect();const travel=window.innerHeight*1.4/.7;const p=Math.min(1,Math.max(0,((window.innerWidth<=760?72:86)-rect.top)/travel));progress.current=p;setAmount(p)};addEventListener('scroll',scroll,{passive:true});addEventListener('resize',scroll);scroll();return()=>{removeEventListener('scroll',scroll);removeEventListener('resize',scroll);mq.removeEventListener('change',updateMotion)}},[]);
 useEffect(()=>{if(reduced)return;let gone=false;let clean=()=>{};(async()=>{const T=await import('three');if(gone||!canvasHost.current)return;const el=canvasHost.current;let r:import('three').WebGLRenderer;try{r=new T.WebGLRenderer({antialias:true,powerPreference:'low-power',alpha:true})}catch{return};r.setPixelRatio(Math.min(devicePixelRatio,1.5));r.setClearColor(0,0);el.appendChild(r.domElement);const s=new T.Scene();const c=new T.OrthographicCamera(-3,3,2,-2,.1,30);c.position.set(0,0,8);const mat=new T.MeshStandardMaterial({color:'#393d3e',metalness:.62,roughness:.42});const g=new T.Group();s.add(g);const geom=new T.BoxGeometry(20,.077,.065);for(let i=0;i<54;i++){const m=new T.Mesh(geom,mat);m.position.y=2.12-i*.08;m.rotation.x=-.055;g.add(m)}const rim=new T.Mesh(new T.BoxGeometry(20,.037,.075),new T.MeshBasicMaterial({color:'#f9813d'}));rim.position.y=-2.17;g.add(rim);s.add(new T.HemisphereLight('#d8e1e2','#080a0b',2));const key=new T.PointLight('#fff5e5',32,20);key.position.set(-1,2,3);s.add(key);const side=new T.PointLight('#738f9f',16,15);side.position.set(4,0,2);s.add(side);const resize=()=>{const w=el.clientWidth,h=el.clientHeight;if(!w||!h)return;r.setSize(w,h,false);c.left=-2.1*w/h;c.right=2.1*w/h;c.top=2.1;c.bottom=-2.1;c.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(el);resize();let frame=0;let last=-1;const draw=()=>{frame=requestAnimationFrame(draw);if(document.hidden||Math.abs(last-progress.current)<.0001)return;last=progress.current;g.position.y=progress.current*4.7;r.render(s,c)};draw();clean=()=>{cancelAnimationFrame(frame);ro.disconnect();geom.dispose();mat.dispose();rim.geometry.dispose();(rim.material as import('three').Material).dispose();r.dispose();r.domElement.remove()}})();return()=>{gone=true;clean()}},[reduced]);
 const skip=()=>{if(runway.current){const y=runway.current.offsetTop+window.innerHeight*1.4/.7-(window.innerWidth<=760?72:86);window.scrollTo({top:y,behavior:reduced?'instant':'smooth'})}};
 return <section ref={runway} className={'intro-runway '+(reduced?'motion-reduced':'')} aria-label="Otwórz stronę rozwijaniem"><div className="intro-sticky"><section className="hero"><img className="hero-image" src="/images/original-16.jpeg" alt="Nowoczesny dom z roletami i bramą garażową" fetchPriority="high"/><div className="hero-shade"/><div className="hero-copy"><p className="eyebrow">ARTAS / ARCHITEKTURA KOMFORTU</p><h1>Świat na zewnątrz.<br/>Spokój <em>wewnątrz.</em></h1><p>Rolety, bramy i pergole. Dopasowane do Twojego domu, zaprojektowane do Twojego życia.</p><a className="primary-btn" href="#oferta">Odkryj możliwości <ArrowDown size={18}/></a></div><div className="hero-bottom"><span>TWÓJ DOM. TWÓJ RYTM.</span><span>PRECYZJA, KTÓRĄ CZUĆ.</span></div></section>{!reduced&&<div className="opening-curtain" style={{pointerEvents:amount>.985?'none':'auto',visibility:amount>.995?'hidden':'visible'}}><div className="curtain-fallback" style={{transform:`translateY(${-amount*115}%)`}}/><div ref={canvasHost} className="curtain-canvas"/><div className="curtain-message" style={{transform:`translateY(${-amount*110}vh)`,opacity:Math.max(0,1-amount*2)}}><p className="eyebrow">KAŻDY DOBRY DZIEŃ ZACZYNA SIĘ OD OTWARCIA</p><div className="opening-title">Otwórz się<br/>na <em>więcej.</em></div><p>Rozwijaj. To Ty masz kontrolę.</p><ChevronsDown size={25}/></div><div className="opening-bottom"><button onClick={skip}>Pomiń otwarcie <ArrowDown size={14}/></button><span>OTWARCIE <strong>{Math.round(amount*100).toString().padStart(2,'0')}%</strong></span><div className="opening-progress" style={{width:`${amount*100}%`}}/></div></div>}</div></section>
}
