'use client';
import {useEffect,useRef,useState} from 'react';
import {Camera,Download,RotateCcw,ImagePlus,Eye} from 'lucide-react';
import type {ModelKind} from '@/lib/artas/catalog';
import {Range} from './Controls';
import {validQuad,gateHeight} from '@/lib/artas/mechanics';
type Pt={x:number;y:number};
const initial:Pt[]=[{x:.36,y:.37},{x:.65,y:.37},{x:.65,y:.84},{x:.36,y:.84}];
export default function PhotoStudio({kind,color,profile,open}:{kind:ModelKind;color:string;profile:number;open:number}){
 const canvas=useRef<HTMLCanvasElement>(null);const upload=useRef<HTMLInputElement>(null);const img=useRef<HTMLImageElement|null>(null);const [src,setSrc]=useState('');const [err,setErr]=useState('');const [points,setPoints]=useState<Pt[]>(initial);const [active,setActive]=useState(-1);const [before,setBefore]=useState(false);const [photoZoom,setPhotoZoom]=useState(1);const [handles,setHandles]=useState(true);const imageUrl=useRef('');const exporter=useRef<()=>void>(()=>{});
 useEffect(()=>()=>{if(imageUrl.current)URL.revokeObjectURL(imageUrl.current)},[]);
 const load=(file:File|undefined)=>{if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){setErr('Wybierz zdjęcie JPG, PNG lub WebP.');return}if(file.size>15*1024*1024){setErr('Wybierz zdjęcie mniejsze niż 15 MB.');return}setErr('');const url=URL.createObjectURL(file);const pic=new Image();pic.onload=()=>{if(pic.width*pic.height>50000000){URL.revokeObjectURL(url);setErr('Zdjęcie ma zbyt dużą rozdzielczość. Wybierz wersję do 50 megapikseli.');return;}if(imageUrl.current)URL.revokeObjectURL(imageUrl.current);imageUrl.current=url;img.current=pic;setSrc(url);setPoints(initial);setPhotoZoom(1)};pic.onerror=()=>{URL.revokeObjectURL(url);setErr('Nie udało się odczytać zdjęcia. Spróbuj innego pliku.')};pic.src=url;};
 useEffect(()=>{const c=canvas.current;if(!c||!img.current)return;const context=c.getContext('2d');if(!context)return;const picture=img.current;const scale=Math.min(1600/picture.width,1200/picture.height,1);c.width=Math.round(picture.width*scale);c.height=Math.round(picture.height*scale);const w=c.width,h=c.height;const p=points.map(p=>({x:p.x*w,y:p.y*h}));
 // A homography maps a unit square into the selected quadrilateral. Geometry remains on device.
 const project=(u:number,v:number)=>{const [a,b,c,d]=p;const dx1=b.x-c.x,dx2=d.x-c.x,dx3=a.x-b.x+c.x-d.x,dy1=b.y-c.y,dy2=d.y-c.y,dy3=a.y-b.y+c.y-d.y;const den=dx1*dy2-dx2*dy1;let g=0,hh=0;if(Math.abs(den)>1e-8){g=(dx3*dy2-dx2*dy3)/den;hh=(dx1*dy3-dx3*dy1)/den;}const z=g*u+hh*v+1;return{x:((b.x-a.x+g*b.x)*u+(d.x-a.x+hh*d.x)*v+a.x)/z,y:((b.y-a.y+g*b.y)*u+(d.y-a.y+hh*d.y)*v+a.y)/z}};
 const poly=(pts:Pt[],fill:string)=>{context.beginPath();pts.forEach((p,i)=>i?context.lineTo(p.x,p.y):context.moveTo(p.x,p.y));context.closePath();context.fillStyle=fill;context.fill()};
 const quad=(x:number,y:number,ww:number,hh:number,fill:string)=>poly([project(x,y),project(x+ww,y),project(x+ww,y+hh),project(x,y+hh)],fill);
 const render=(guides:boolean)=>{context.clearRect(0,0,w,h);context.drawImage(picture,0,0,w,h);if(!before){quad(0,0,1,1,'#14181b');const isGate=kind==='gate'||kind==='industrial';const nominal=isGate?gateHeight(profile)*1000:2100;const count=Math.ceil(nominal/profile);const visible=1-open/100;const ph=1/count;
 for(let i=0;i<count;i++){const y=i*ph-open/100;if(y+ph<=0)continue;const start=Math.max(0,y),end=Math.min(visible,y+ph);if(end<=start)continue;quad(.016,start,.968,end-start,color);quad(.016,start,.968,Math.min(.002,end-start),'rgba(255,255,255,.3)');quad(.016,end-.003,.968,.003,'rgba(0,0,0,.55)');if(!isGate)quad(.02,start+Math.min(.004,(end-start)/3),.96,Math.min(.004,(end-start)/3),'rgba(255,255,255,.08)')}
 quad(0,0,.018,1,color);quad(.982,0,.018,1,color);if(!isGate)quad(0,0,1,.07,color);quad(.016,Math.max(0,visible-.008),.968,.008,'#2d3031');quad(.019,0,.014,1,'rgba(0,0,0,.3)');
 }if(guides){context.strokeStyle='#ff985b';context.lineWidth=2;context.setLineDash([5,5]);context.beginPath();p.forEach((v,i)=>i?context.lineTo(v.x,v.y):context.moveTo(v.x,v.y));context.closePath();context.stroke();context.setLineDash([]);p.forEach((v,i)=>{context.beginPath();context.arc(v.x,v.y,10,0,Math.PI*2);context.fillStyle='#f9813d';context.fill();context.fillStyle='#121212';context.font='bold 12px Arial';context.textAlign='center';context.fillText(String(i+1),v.x,v.y+4)})}};render(handles);exporter.current=()=>{render(false);const a=document.createElement('a');a.download='ARTAS-moj-dom.png';a.href=c.toDataURL('image/png');a.click();render(handles)};
 },[src,points,kind,color,profile,open,before,handles]);
 const move=(clientX:number,clientY:number,index:number)=>{const r=canvas.current?.getBoundingClientRect();if(!r)return;const next={x:Math.max(.01,Math.min(.99,(clientX-r.left)/r.width)),y:Math.max(.01,Math.min(.99,(clientY-r.top)/r.height))};setPoints(prev=>{const n=prev.map((p,i)=>i===index?next:p);if(!validQuad(n))return prev;return n})};
 return <div className="photo-studio"><input ref={upload} type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>load(e.target.files?.[0])} className="sr-only" aria-label="Dodaj zdjęcie domu"/>{!src?<button className="photo-drop" onClick={()=>upload.current?.click()} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();load(e.dataTransfer.files[0])}}><span className="photo-icon"><Camera size={42} strokeWidth={1}/></span><h3>To może być Twój dom.</h3><p>Dodaj zdjęcie i przymierz wybrane rozwiązanie.</p><span className="primary-btn">Dodaj zdjęcie <ImagePlus size={18}/></span><small>JPG, PNG lub WebP · do 15 MB<br/>Zdjęcie pozostaje w Twojej przeglądarce.</small></button>:<><div className="photo-toolbar"><button onClick={()=>upload.current?.click()}><ImagePlus size={16}/> Zmień zdjęcie</button><button aria-pressed={before} onClick={()=>setBefore(!before)}><Eye size={16}/>{before?'Pokaż wizualizację':'Porównaj z oryginałem'}</button><button onClick={()=>setPoints(initial)} aria-label="Przywróć narożniki"><RotateCcw size={16}/></button><button onClick={()=>exporter.current()} aria-label="Pobierz wizualizację PNG"><Download size={16}/></button></div><div className="photo-viewport"><div className="photo-transform" style={{width:`${photoZoom*100}%`}}><canvas ref={canvas} className="photo-canvas" aria-label="Zdjęcie domu z wybranym produktem" onPointerDown={e=>{if(!handles)return;const r=e.currentTarget.getBoundingClientRect();const idx=points.findIndex(p=>Math.hypot(p.x*r.width-(e.clientX-r.left),p.y*r.height-(e.clientY-r.top))<28);if(idx!==-1){setActive(idx);e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(active!==-1)move(e.clientX,e.clientY,active)}} onPointerUp={()=>setActive(-1)} onPointerCancel={()=>setActive(-1)}/></div></div><div className="photo-instructions"><p>Przeciągnij 4 narożniki na krawędzie okna lub bramy. To przymiarka perspektywiczna na zdjęciu.</p><button onClick={()=>setHandles(!handles)}>{handles?'Ukryj narożniki':'Edytuj narożniki'}</button></div><Range label="Przybliżenie zdjęcia" value={photoZoom} min={1} max={2.5} step={.1} unit="×" onChange={setPhotoZoom}/><details className="photo-fine"><summary>Precyzyjne ustawienie narożników</summary><div className="corner-grid">{points.map((p,i)=><div key={i}><b>Narożnik {i+1}</b>{(['x','y'] as const).map(axis=><label key={axis}>{axis.toUpperCase()} %<input type="number" min={1} max={99} value={Math.round(p[axis]*100)} onChange={e=>{const v=Number(e.target.value);if(Number.isFinite(v))setPoints(prev=>{const n=prev.map((q,j)=>j===i?{...q,[axis]:Math.max(.01,Math.min(.99,v/100))}:q);return validQuad(n)?n:prev})}}/></label>)}</div>)}</div></details></>}{err&&<p role="alert" className="error-text">{err}</p>}</div>
}
