'use client';
import {useEffect,useRef,useState} from 'react';
import {gateHeight,MODEL_OPENING_DURATION_MS} from '@/lib/artas/mechanics';
import type {ModelKind} from '@/lib/artas/catalog';
export type SceneProps={kind:ModelKind;color:string;profile:number;open:number;explode?:number;cut?:boolean;zoom?:number;assembled?:number;selected?:string;onPick?:(id:string)=>void;className?:string;view?:'front'|'angle'};
export default function ProductScene(props:SceneProps){
 const host=useRef<HTMLDivElement>(null);const state=useRef(props);useEffect(()=>{state.current=props});const [error,setError]=useState(false);const [ready,setReady]=useState(false);
 useEffect(()=>{let disposed=false,cleanup=()=>{};
 (async()=>{setReady(false);setError(false);const [T,{OrbitControls},{RoomEnvironment},{createProduct}]=await Promise.all([import('three'),import('three/addons/controls/OrbitControls.js'),import('three/addons/environments/RoomEnvironment.js'),import('@/lib/artas/model')]);
 if(disposed||!host.current)return;const el=host.current;let renderer:import('three').WebGLRenderer;try{renderer=new T.WebGLRenderer({antialias:true,alpha:true,powerPreference:'low-power'});}catch{setError(true);return;}
 renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));renderer.setClearColor('#131617',0);renderer.localClippingEnabled=true;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.45;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;el.appendChild(renderer.domElement);
 const scene=new T.Scene();const camera=new T.PerspectiveCamera(35,1,.05,100);const init=props.kind==='pergola'?new T.Vector3(5.6,3.7,6.3):new T.Vector3(3.4,1.9,5.8);if(props.view==='front')init.set(.15,.25,7);camera.position.copy(init);camera.lookAt(0,.1,0);
 const pmrem=new T.PMREMGenerator(renderer);const room=new RoomEnvironment();const env=pmrem.fromScene(room,.04);scene.environment=env.texture;room.dispose();
 scene.add(new T.HemisphereLight('#fff7eb','#596676',2));const key=new T.DirectionalLight('#fff5e5',4.5);key.position.set(-3,6,5);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=5;key.shadow.camera.bottom=-5;key.shadow.normalBias=.03;scene.add(key);const rim=new T.DirectionalLight('#a2c6dd',3);rim.position.set(4,2,-3);scene.add(rim);
 const floor=new T.Mesh(new T.PlaneGeometry(40,40),new T.ShadowMaterial({opacity:.28}));floor.rotation.x=-Math.PI/2;floor.position.y=props.kind==='gate'||props.kind==='industrial'?-gateHeight(props.profile)/2-.015:props.kind==='pergola'?-1.215:-1.065;floor.receiveShadow=true;scene.add(floor);
 const model=createProduct(props.kind,props.color,props.profile);scene.add(model.root);
 const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enableZoom=false;controls.enablePan=false;controls.minPolarAngle=.25;controls.maxPolarAngle=Math.PI*.72;controls.target.set(0,.1,0);controls.enabled=props.view!=='front';
 const resize=()=>{if(!el.clientWidth||!el.clientHeight)return;renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};const ro=new ResizeObserver(resize);ro.observe(el);resize();
 let visible=true;const io=new IntersectionObserver(([e])=>{visible=e.isIntersecting},{rootMargin:'150px'});io.observe(el);
 const ray=new T.Raycaster();let down={x:0,y:0};const pd=(e:PointerEvent)=>{down={x:e.clientX,y:e.clientY}};const pu=(e:PointerEvent)=>{if(!state.current.onPick||Math.hypot(e.clientX-down.x,e.clientY-down.y)>8)return;const r=el.getBoundingClientRect();ray.setFromCamera(new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),camera);const hit=ray.intersectObject(model.root,true).find(h=>h.object.userData.partId);if(hit)state.current.onPick?.(hit.object.userData.partId);};renderer.domElement.addEventListener('pointerdown',pd);renderer.domElement.addEventListener('pointerup',pu);
 const contextLost=(e:Event)=>{e.preventDefault();setError(true)};renderer.domElement.addEventListener('webglcontextlost',contextLost);
   let frame=0;let shownOpen=state.current.open;let animationFrom=state.current.open;let animationTo=state.current.open;let animationElapsed=MODEL_OPENING_DURATION_MS;let last=performance.now();const animate=(now:number)=>{frame=requestAnimationFrame(animate);if(!visible||document.hidden){last=now;return;}const dt=Math.min((now-last)/1000,.05);last=now;const s=state.current;if(s.open!==animationTo){animationFrom=shownOpen;animationTo=s.open;animationElapsed=0;}animationElapsed=Math.min(animationElapsed+dt*1000,MODEL_OPENING_DURATION_MS);const t=animationElapsed/MODEL_OPENING_DURATION_MS;const eased=t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2;shownOpen=animationFrom+(animationTo-animationFrom)*eased;model.update(shownOpen,s.explode??0,s.cut??false,s.assembled,s.selected);camera.zoom=s.zoom??1;camera.updateProjectionMatrix();controls.update();renderer.render(scene,camera);};frame=requestAnimationFrame(animate);setReady(true);
 cleanup=()=>{cancelAnimationFrame(frame);ro.disconnect();io.disconnect();controls.dispose();renderer.domElement.removeEventListener('pointerdown',pd);renderer.domElement.removeEventListener('pointerup',pu);renderer.domElement.removeEventListener('webglcontextlost',contextLost);model.dispose();floor.geometry.dispose();floor.material.dispose();env.dispose();pmrem.dispose();renderer.dispose();renderer.domElement.remove();};
 })().catch(()=>{if(!disposed)setError(true)});return()=>{disposed=true;cleanup()};
 },[props.kind,props.color,props.profile,props.view]);
 return <div className={'product-scene '+(props.className??'')} ref={host} role="img" aria-label={'Interaktywny model 3D: '+props.kind+'. Przeciągnij, aby obrócić.'}>{!ready&&!error&&<div className="scene-loading"><span/>Przygotowuję model 3D…</div>}{error&&<div className="scene-loading">Podgląd 3D wymaga WebGL.<br/>Opisy i konfiguracja są dostępne poniżej.</div>}</div>
}
