'use client';
import {useEffect,useRef,useState} from 'react';
import {flushSync} from 'react-dom';
import {Box,Camera,Layers3,Move,RotateCcw,ScanLine,Maximize,Minimize,Play,ArrowUpRight} from 'lucide-react';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Dialog,DialogClose,DialogContent,DialogDescription,DialogTitle} from '@/components/ui/dialog';
import {Colors,Choice,Range} from './Controls';
import ProductScene from './ProductScene';
import PhotoStudio from './PhotoStudio';
import {defaultStudioColorIndex,modelNames,nominalProfiles,palette,products,type ModelKind} from '@/lib/artas/catalog';
import {X} from 'lucide-react';
import {gateHeight,MODEL_OPENING_DURATION_MS} from '@/lib/artas/mechanics';
export const technicalSources=[{name:'Aluprof — system SKP, przekroje i profile',url:'https://aluprof.com/files/product_documents/skp_en.pdf'},{name:'Aluprof — MB-OpenSky 140, budowa pergoli',url:'https://fasada.eu/wp-content/uploads/2022/08/mb-open_sky_140_de_580.pdf'},{name:'BramTECH — rysunek prowadzenia standardowego',url:'https://www.bramtech.com.pl/files/download/5ff439ba2a985.pdf'},{name:'BUDVAR — wymiary paneli bram segmentowych',url:'https://budvar.pl/produkty/bramy-garazowe'}];
export function SourceNote(){return <details className="source-note"><summary>O modelach i dokumentacji technicznej <ArrowUpRight size={13}/></summary><p>Modele poglądowe pokazują zasadę działania i podzespoły. Nie są dokumentacją wykonawczą ani odwzorowaniem wszystkich detali producenta. Wymiary nominalne i dostępność kolorów wymagają potwierdzenia dla wybranego systemu.</p><ul>{technicalSources.map(s=><li key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.name} ↗</a></li>)}</ul></details>}
export default function Studio({initialKind='roller',compact=false,initialExplode=0,webmcp=false}:{initialKind?:ModelKind;compact?:boolean;initialExplode?:number;webmcp?:boolean}){
 const [kind,setKind]=useState<ModelKind>(initialKind);const [color,setColor]=useState(defaultStudioColorIndex);const [profile,setProfile]=useState(nominalProfiles(initialKind)[0]??200);const [open,setOpen]=useState(0);const [explode,setExplode]=useState(initialExplode);const [cut,setCut]=useState(false);const [zoom,setZoom]=useState(1);const [view,setView]=useState<'angle'|'front'>('angle');const [mode,setMode]=useState('model');const [full,setFull]=useState(false);const [cycle,setCycle]=useState(false);const ref=useRef<HTMLDivElement>(null);const cycleTimer=useRef<ReturnType<typeof setInterval>|null>(null);const current=useRef({kind,color,profile,open,explode,cut,zoom});useEffect(()=>{current.current={kind,color,profile,open,explode,cut,zoom}});
 const changeKind=(k:ModelKind)=>{setKind(k);setColor(defaultStudioColorIndex);setProfile(nominalProfiles(k)[0]??200);setOpen(0);setExplode(0);setCycle(false);if(k==='pergola')setMode('model')};
 useEffect(()=>{if(!cycle)return;const start=current.current.open<50?100:0;let v=start;const tick=()=>{setOpen(v);v=v===100?0:100};const first=setTimeout(tick,0);cycleTimer.current=setInterval(tick,MODEL_OPENING_DURATION_MS);return()=>{clearTimeout(first);if(cycleTimer.current)clearInterval(cycleTimer.current)}},[cycle]);
 useEffect(()=>{const handler=()=>setFull(document.fullscreenElement===ref.current);document.addEventListener('fullscreenchange',handler);return()=>document.removeEventListener('fullscreenchange',handler)},[]);
 const fullscreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await ref.current?.requestFullscreen()}catch{setFull(v=>!v)}};
 useEffect(()=>{if(!webmcp)return;const context=(document as unknown as {modelContext?:{registerTool:(tool:Record<string,unknown>,opts:{signal:AbortSignal})=>void}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();
 const get=()=>({...current.current,colorName:palette[current.current.color].name,availableProfiles:nominalProfiles(current.current.kind)});
 try{context.registerTool({name:'read_artas_configuration',title:'Odczytaj konfigurację ARTAS',description:'Read the current visible product configuration. Does not access photos.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:get},{signal:life.signal});
 context.registerTool({name:'configure_artas_product',title:'Skonfiguruj produkt ARTAS',description:'Update the visible 3D product, finish, nominal profile and opening. Does not submit an order or upload a photo.',inputSchema:{type:'object',properties:{kind:{type:'string',enum:Object.keys(modelNames)},colorIndex:{type:'integer',minimum:0,maximum:15},profile:{type:'number'},opening:{type:'number',minimum:0,maximum:100},halfSection:{type:'boolean'}},additionalProperties:false},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input))throw new Error('Invalid input');const a=input as Record<string,unknown>;if(Object.keys(a).some(k=>!['kind','colorIndex','profile','opening','halfSection'].includes(k)))throw new Error('Unknown option');const k=(a.kind??current.current.kind) as ModelKind;if(!Object.keys(modelNames).includes(k))throw new Error('Unknown product');const co=a.colorIndex??current.current.color;if(!Number.isInteger(co)||Number(co)<0||Number(co)>15)throw new Error('Invalid colour');const pr=a.profile??(a.kind?nominalProfiles(k)[0]??200:current.current.profile);if(k!=='pergola'&&!nominalProfiles(k).includes(Number(pr)))throw new Error('Profile incompatible with product');const op=a.opening??current.current.open;if(typeof op!=='number'||op<0||op>100||!Number.isFinite(op))throw new Error('Invalid opening');if(a.halfSection!==undefined&&typeof a.halfSection!=='boolean')throw new Error('Invalid section');flushSync(()=>{setKind(k);setColor(Number(co));setProfile(Number(pr));setOpen(op);setCut((a.halfSection??current.current.cut) as boolean);setCycle(false);setMode('model')});return get();}},{signal:life.signal})}catch{/* Unsupported registries do not block the customer interface. */}return()=>life.abort();},[webmcp]);
 const isGate=kind==='gate'||kind==='industrial';const isGrille=kind==='commercial-grille';const product=products.find(p=>p.model===kind);
 return <div className={'studio '+(compact?'compact':'')+(full?' studio-fullscreen':'')} ref={ref}>
  <Tabs value={mode} onValueChange={v=>{setMode(v);setCycle(false)}}>
   <div className="studio-toolbar"><TabsList className="artas-tabs"><TabsTrigger value="model"><Box size={15}/> Model 3D</TabsTrigger><TabsTrigger value="photo" disabled={kind==='pergola'}><Camera size={15}/> Na moim domu</TabsTrigger></TabsList><span className="live-render">STUDIO ARTAS <span>01—3D</span></span></div>
   <div className="studio-layout"><div className="studio-display">
    <TabsContent value="model" className="scene-tab"><div className="scene-meta"><span>{modelNames[kind]}</span><span>{isGate?'3100 × '+Math.round(gateHeight(profile)*1000):kind==='pergola'?'3500 × 2600':kind==='rolling-gate'||isGrille?'2800 × 2100':'1700 × 2100'} mm · model</span></div><ProductScene kind={kind} color={palette[color].hex} profile={profile} open={open} explode={explode} cut={cut} zoom={zoom} view={view}/><div className="model-label"><span>{cut?'01 / WIDOK WNĘTRZA':explode>.1?'02 / WIDOK PODZESPOŁÓW':'01 / WIDOK ZŁOŻONY'}</span><strong>{kind==='pergola'?Math.round(open*1.35)+'°':profile+' mm'}</strong><small>{kind==='pergola'?'kąt nachylenia dachu':isGate?'wysokość panelu':'wysokość profilu'}</small></div><div className="scene-tools"><button className={explode>.1?'active':''} onClick={()=>{setCycle(false);setOpen(0);setExplode(explode>.1?0:1)}} title="Rozsuń lub złóż podzespoły"><Layers3 size={16}/>{explode>.1?'Złóż':'Rozłóż'}</button><button aria-label="Zmień widok modelu" onClick={()=>setView(view==='front'?'angle':'front')}><ScanLine size={16}/></button><button aria-label={full?'Wyjdź z pełnego ekranu':'Pełny ekran'} onClick={fullscreen}>{full?<Minimize size={16}/>:<Maximize size={16}/>}</button><span><Move size={13}/> Obracaj przeciągnięciem</span></div></TabsContent>
    <TabsContent value="photo"><PhotoStudio kind={kind} color={palette[color].hex} profile={profile} open={open}/></TabsContent>
   </div><aside className="studio-controls"><div className="control-title"><span>TWÓJ PROJEKT</span><button aria-label="Przywróć ustawienia konfiguratora" onClick={()=>{changeKind(initialKind);setColor(defaultStudioColorIndex);setCut(false);setZoom(1);setView('angle')}}><RotateCcw size={16}/></button></div><Choice label="Rozwiązanie" value={kind} onChange={v=>changeKind(v as ModelKind)} options={Object.entries(modelNames).map(([value,label])=>({value,label}))}/><Colors index={color} onChange={setColor}/>{kind!=='pergola'&&<Choice label={isGate?'Wysokość panelu':'Wysokość profilu'} value={String(profile)} onChange={v=>setProfile(Number(v))} options={nominalProfiles(kind).map(p=>({value:String(p),label:p+' mm'+(p===39?' · PA39':p===43?' · PA43':p===52?' · PA52':'' )}))}/>}<Range label={kind==='pergola'?'Otwarcie dachu':'Otwarcie'} value={open} onChange={v=>{setCycle(false);setOpen(v)}}/>{mode==='model'&&<><Range label="Przybliżenie" value={zoom} min={.65} max={1.8} step={.05} unit="×" onChange={setZoom}/><div className="switch-field"><label htmlFor={compact?'compact-cut':'studio-cut'}><ScanLine size={16}/> Półprzekrój</label><Switch id={compact?'compact-cut':'studio-cut'} checked={cut} onCheckedChange={setCut}/></div><button className={'outline-btn '+(cycle?'active':'')} onClick={()=>{setExplode(0);setCycle(!cycle)}}><Play size={15}/>{cycle?'Zatrzymaj pokaz':'Zobacz w ruchu'}</button></>}{product&&<a className="product-detail-link" href={'/produkty/'+product.slug}>Poznaj {kind==='pergola'?'pergolę':'rozwiązanie'}<ArrowUpRight size={15}/></a>}<p className="technical-note">{isGate?'Model ma pełne moduły paneli. Jego wysokość zmienia się wraz z wybranym panelem; rzeczywisty dobór zależy od systemu.':kind==='pergola'?'Zakres demonstracyjny 0–135°.':'Wymiary profili są nominalne. Gabaryty dobiera się do konkretnego systemu.'}</p></aside></div>
  </Tabs>{!compact&&<SourceNote/>}</div>
}
export function ModelDialog({kind,onClose}:{kind:ModelKind|null;onClose:()=>void}){return <Dialog open={!!kind} onOpenChange={v=>{if(!v)onClose()}}><DialogContent className="model-dialog" showCloseButton={false}><div className="model-dialog-header"><div><DialogTitle>{kind?modelNames[kind]:''} — od środka</DialogTitle><DialogDescription>Obróć, rozsuń podzespoły i odkryj zasadę działania.</DialogDescription></div><DialogClose className="icon-button" aria-label="Zamknij wizualizację"><X size={22}/></DialogClose></div>{kind&&<Studio key={kind} initialKind={kind} compact initialExplode={1}/>}<SourceNote/></DialogContent></Dialog>}
