'use client';
import {useEffect,useRef,useState} from 'react';
import {Play,RotateCcw,Zap,Check,ArrowRight} from 'lucide-react';
import {Progress} from '@/components/ui/progress';
import {Choice} from './Controls';
import {safeWireMove,type Point} from '@/lib/artas/mechanics';
const wires=[{name:'Napęd',symbol:'M',color:'#f9813d'},{name:'Fotokomórka',symbol:'F',color:'#8dbddb'},{name:'Lampa',symbol:'L',color:'#ddc071'},{name:'Przycisk',symbol:'P',color:'#a1c5a6'}];
const paths=wires.map((_,i)=>{const y=105+i*88;return [{x:112,y},{x:216,y},{x:216,y:y-22},{x:470,y:y-22},{x:470,y},{x:648,y}]});
export default function WiringGame(){const [running,setRunning]=useState(false);const [done,setDone]=useState<number[]>([]);const [faults,setFaults]=useState(0);const [active,setActive]=useState(-1);const [trail,setTrail]=useState<Point[]>([]);const [tip,setTip]=useState<Point|null>(null);const [seconds,setSeconds]=useState(0);const [difficulty,setDifficulty]=useState('relax');const [message,setMessage]=useState('Połącz 4 obwody. Prowadź przewód wewnątrz podświetlonego kanału.');const svg=useRef<SVGSVGElement>(null);const last=useRef<Point|null>(null);const won=done.length===4;const lost=faults>=3;
 useEffect(()=>{if(!running||won||lost)return;const t=setInterval(()=>setSeconds(s=>s+1),1000);return()=>clearInterval(t)},[running,won,lost]);
 const reset=()=>{setRunning(true);setDone([]);setFaults(0);setActive(-1);setTrail([]);setTip(null);last.current=null;setSeconds(0);setMessage('Chwyć złącze po lewej i doprowadź przewód do pasującego portu.');};
 const begin=(i:number)=>{if(!running||won||lost||done.includes(i))return;setActive(i);const p=paths[i][0];last.current=p;setTip(p);setTrail([p]);setMessage(wires[i].name+': trzymaj się kanału. Strzałki również przesuwają końcówkę.');svg.current?.focus()};
 const fail=()=>{setFaults(f=>f+1);setActive(-1);setTip(null);setTrail([]);last.current=null;setMessage('Dotknięcie krawędzi! Rozpocznij ten przewód ponownie.');};
 const move=(p:Point)=>{if(active<0||!last.current)return;if(!safeWireMove(last.current,p,paths[active],difficulty==='relax'?21:12)){fail();return}last.current=p;setTip(p);setTrail(a=>[...a,p]);};
 const finish=()=>{if(active<0||!tip)return;const goal=paths[active].at(-1)!;if(Math.hypot(tip.x-goal.x,tip.y-goal.y)<24){setDone(a=>[...a,active]);setMessage(wires[active].name+' podłączony. '+(done.length===3?'Wszystkie obwody gotowe!':'Wybierz kolejny obwód.'));}else setMessage('Przewód odłożony. Spróbuj doprowadzić go do portu po prawej.');setActive(-1);setTip(null);setTrail([]);last.current=null;};
 const point=(e:React.PointerEvent)=>{const m=svg.current?.getScreenCTM();if(!m)return{x:0,y:0};const p=new DOMPoint(e.clientX,e.clientY).matrixTransform(m.inverse());return{x:p.x,y:p.y}};
 return <div className="game-shell wiring"><div className="game-console"><div className="console-label"><Zap size={16}/> ARTAS CONNECT <span>SYMULATOR 24 V</span></div><div className="game-stats"><span><b>{String(seconds).padStart(2,'0')}s</b> czas</span><span><b>{done.length}/4</b> obwody</span><span className={faults?'faults':''}><b>{faults}/3</b> dotknięcia</span></div></div><div className={'wiring-board '+(lost?'board-failed':'')}><svg ref={svg} viewBox="0 0 760 465" role="application" aria-label="Plansza połączeń. Wybierz przewód poniżej, przesuwaj strzałkami i zatwierdź Enter." tabIndex={0} onPointerDown={e=>{const p=point(e);const i=paths.findIndex(path=>Math.hypot(p.x-path[0].x,p.y-path[0].y)<30);if(i!==-1){begin(i);e.currentTarget.setPointerCapture(e.pointerId)}}} onPointerMove={e=>{if(active!==-1)move(point(e))}} onPointerUp={finish} onPointerCancel={()=>{setActive(-1);setTrail([]);setTip(null)}} onKeyDown={e=>{if(active<0)return;const dirs:Record<string,number[]>={ArrowLeft:[-6,0],ArrowRight:[6,0],ArrowUp:[0,-6],ArrowDown:[0,6]};if(dirs[e.key]&&tip){e.preventDefault();move({x:tip.x+dirs[e.key][0],y:tip.y+dirs[e.key][1]})}if(e.key==='Enter'){e.preventDefault();finish()}if(e.key==='Escape'){setActive(-1);setTip(null);setTrail([])}}}>
 <defs><pattern id="board-grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="1" cy="1" r=".6" fill="#ffffff17"/></pattern><linearGradient id="board-surface" x2="1" y2="1"><stop stopColor="#273630"/><stop offset="1" stopColor="#14221d"/></linearGradient></defs><rect x="14" y="14" width="732" height="440" rx="15" fill="#080b0a"/><rect x="9" y="5" width="742" height="439" rx="15" fill="url(#board-surface)" stroke="#53675b"/><rect x="15" y="14" width="730" height="420" fill="url(#board-grid)"/><text x="38" y="48" fill="#a3b2a8" fontSize="13" fontFamily="monospace">ARTAS / LOGIC BOARD</text><text x="543" y="48" fill="#a3b2a8" fontSize="12" fontFamily="monospace">24 V • DEMO ONLY</text>{[[29,25],[730,25],[29,423],[730,423]].map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r="6" fill="#73837a"/><path d={`M${x-3} ${y}h6`} stroke="#223128" strokeWidth="2"/></g>)}{paths.map((path,i)=>{const d=path.map((p,j)=>(j?'L':'M')+p.x+','+p.y).join(' ');return <g key={i} opacity={!running?.6:1}><path d={d} fill="none" stroke="#09130e" strokeWidth={difficulty==='relax'?48:30} strokeLinejoin="round" strokeLinecap="round"/><path d={d} fill="none" stroke={wires[i].color} strokeOpacity={done.includes(i)?1:active===i?.32:.11} strokeWidth={done.includes(i)?7:2} strokeDasharray={done.includes(i)?undefined:'3 6'} strokeLinejoin="round"/>{[path[0],path.at(-1)!].map((p,j)=><g key={j}><rect x={p.x-29} y={p.y-28} width="58" height="56" rx="6" fill="#34443b" stroke="#6e7d73"/><circle cx={p.x} cy={p.y} r="16" fill="#0d1612" stroke={wires[i].color} strokeWidth="4"/><text x={p.x} y={p.y+5} textAnchor="middle" fill={wires[i].color} fontSize="14" fontFamily="monospace">{done.includes(i)?'✓':wires[i].symbol}</text></g>)}<text x="157" y={path[0].y+35} fontSize="12" fill="#adbbb1" fontFamily="monospace">{wires[i].name.toUpperCase()}</text></g>})}{active>=0&&trail.length>0&&<><polyline points={trail.map(p=>p.x+','+p.y).join(' ')} fill="none" stroke={wires[active].color} strokeWidth="6" strokeLinejoin="round" strokeLinecap="round"/>{tip&&<circle cx={tip.x} cy={tip.y} r="9" stroke="#fff" strokeWidth="2" fill={wires[active].color}/>}</>}
 </svg>{(!running||won||lost)&&<div className="game-overlay"><div className="game-overlay-card">{won?<Check size={32}/>:<Zap size={32}/>}<h3>{won?'Dobre połączenie.':lost?'Jeszcze jedna próba?':'Pewna ręka. Dobry kontakt.'}</h3><p>{won?`4 obwody gotowe w ${seconds} s. Wynik: ${Math.max(0,1000-faults*100-seconds*2)} pkt.`:lost?'Trzy dotknięcia krawędzi. Spróbuj spokojniejszego tempa.':'Chwyć przewód i przeprowadź go przez kanał. Uważaj na krawędzie.'}</p><button className="primary-btn" onClick={reset}>{running?'Zagraj ponownie':'Rozpocznij grę'} <Play size={16}/></button></div></div>}</div><div className="game-bottom"><div className="game-message" role="status">{message}</div><div className="game-actions"><Choice label="Poziom precyzji" value={difficulty} options={[{value:'relax',label:'Spokojnie'},{value:'precise',label:'Precyzyjnie'}]} onChange={v=>{setDifficulty(v);setActive(-1);setTip(null);setTrail([]);}}/><button className="icon-button" onClick={reset} aria-label="Zacznij grę od nowa"><RotateCcw size={18}/></button></div><Progress value={done.length*25} aria-label="Postęp podłączania"/><details className="keyboard-controls"><summary>Sterowanie klawiaturą</summary><p>Wybierz przewód, użyj strzałek w planszy i naciśnij Enter przy docelowym porcie.</p><div className="wire-buttons">{wires.map((w,i)=><button key={w.name} disabled={!running||won||lost||done.includes(i)} onClick={()=>begin(i)}>{w.symbol} · {w.name}{done.includes(i)?<Check size={14}/>:<ArrowRight size={14}/>}</button>)}</div></details><small className="technical-note">Fikcyjna centrala treningowa. Gra nie jest schematem podłączania rzeczywistej automatyki.</small></div></div>
}
