import Link from 'next/link';
import {notFound} from 'next/navigation';
import type {Metadata} from 'next';
import {ArrowLeft,ArrowUpRight,Check} from 'lucide-react';
import {products} from '@/lib/artas/catalog';
import {Header,Footer} from '@/components/artas/Shell';
import Studio from '@/components/artas/Studio';
export function generateStaticParams(){return products.map(p=>({slug:p.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const p=products.find(p=>p.slug===slug);return{title:p?p.name+' — ARTAS':'Nie znaleziono — ARTAS',description:p?.description}}
export default async function ProductPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const p=products.find(p=>p.slug===slug);if(!p)notFound();const related=products.filter(x=>x.group===p.group&&x.slug!==p.slug).slice(0,3);return <main id="top"><Header/><section className="section product-page" id="oferta"><Link className="back-link" href="/#oferta"><ArrowLeft size={15}/>Wszystkie rozwiązania</Link><div className={'product-intro '+(p.image===undefined?'text-only':'')}><div><p className="eyebrow">ARTAS / {p.group==='architecture'?'BRAMY, PERGOLE I KRATY':p.group==='outside'?'OSŁONY ZEWNĘTRZNE':'OSŁONY OKIENNE'}</p><h1>{p.name}</h1><h2>{p.lead}</h2><p className="product-description">{p.description}</p><a className="primary-btn" href={'mailto:artasrolety@gmail.com?subject='+encodeURIComponent('Zapytanie: '+p.name)}>Zapytaj o rozwiązanie <ArrowUpRight size={18}/></a></div>{p.image!==undefined&&<div className="product-page-image"><img src={'/images/original-'+p.image+'.jpeg'} alt={p.name}/><span>ARTAS / {p.name}</span></div>}</div><div className="product-features">{p.features.map(f=><div key={f}><Check size={20}/>{f}</div>)}</div><div className="product-details"><h2>Przemyślany wybór.</h2><p>{p.detail}</p></div>{p.model&&<div id="konstrukcja"><div className="section-heading"><div><p className="eyebrow">ZOBACZ, JAK TO DZIAŁA</p><h2>Konstrukcja pod kontrolą.</h2></div></div><Studio initialKind={p.model}/></div>}{related.length>0&&<div className="related-products"><p className="eyebrow">POZNAJ TAKŻE</p>{related.map(r=><a key={r.slug} className="catalog-row" href={'/produkty/'+r.slug}><span>{r.name}</span><ArrowUpRight size={20}/></a>)}</div>}</section><Footer/></main>}
