'use client';
import {useState} from 'react';
import {ArrowUpRight,Box,Plus,Minus,X,ChevronLeft,ChevronRight,Sun,ShieldCheck,SlidersHorizontal,Snowflake,Radio,Settings2,Wrench} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import Opening from '@/components/artas/Opening';
import {Header,Footer} from '@/components/artas/Shell';
import Studio,{ModelDialog} from '@/components/artas/Studio';
import GameSlot from '@/components/artas/GameSlot';
import {products,type Product,type ModelKind} from '@/lib/artas/catalog';
const gallery=[{i:18,title:'Brama garażowa',cat:'BRAMY'},{i:27,title:'Rolety w nowoczesnej elewacji',cat:'ROLETY'},{i:24,title:'Krata handlowa',cat:'KRATY'},{i:23,title:'Brama w obiekcie przemysłowym',cat:'PRZEMYSŁ'},{i:17,title:'Osłony w budynku użytkowym',cat:'OSŁONY'},{i:20,title:'Zabudowa wielorodzinna',cat:'FASADY'},{i:21,title:'Montaż bramy przemysłowej',cat:'PRZEMYSŁ'},{i:22,title:'Modernizacja budynku',cat:'ROLETY'},{i:26,title:'Rolety w zabudowie miejskiej',cat:'ROLETY'},{i:28,title:'Dom jednorodzinny',cat:'ROLETY'}];
const games=[{id:'rush',num:'01',tag:'ZRĘCZNOŚĆ',title:'Gate Rush',desc:'Wjedź przed zamykającą się bramą. Czytanie lampy i dobry moment są ważniejsze od samej prędkości.',label:'Gate Rush — gra zręcznościowa'},{id:'monter',num:'02',tag:'MONTAŻ',title:'Monter: 600 N',desc:'Wykonaj siedem jawnie opisanych kontroli i sprawdź konstrukcję w teście otwarcia.',label:'Monter 600 N — ćwiczenie montażowe'},{id:'learn',num:'03',tag:'DECYZJE',title:'Diagnostyka bramy',desc:'Ustaw trzy punkty ruchu, dopasuj konfigurację do sytuacji i wybierz bezpieczne reakcje.',label:'Diagnostyka bramy — ćwiczenie decyzyjne'}] as const;
type GameId=typeof games[number]['id'];
export default function Home(){const [model,setModel]=useState<ModelKind|null>(null);const [showAll,setShowAll]=useState(false);const [photo,setPhoto]=useState<number|null>(null);const [game,setGame]=useState<GameId>('rush');const activeGame=games.find(g=>g.id===game)!;
 const card=(p:Product,number?:string)=><article className="product-card" key={p.slug}><div className="product-card-image">{number&&<span className="card-number">{number}</span>}<img src={'/images/original-'+p.image+'.jpeg'} alt={p.name} loading="lazy"/><span className="product-tag">{p.group==='outside'?'OSŁONY ZEWNĘTRZNE':'ARCHITEKTURA ZEWNĘTRZNA'}</span></div><div className="product-card-copy"><a href={'/produkty/'+p.slug}><h3>{p.name}<ArrowUpRight size={21}/></h3></a><p>{p.lead}</p>{p.model&&<button onClick={()=>setModel(p.model!)} className="model-trigger"><Box size={16}/> Zobacz konstrukcję 3D<Plus size={17}/></button>}</div></article>;
 return <main id="top"><Header/><Opening/><div className="brand-strip"><span>Przestrzeń, która działa dla Ciebie.</span><div><span><Sun size={17}/> Światło</span><span><ShieldCheck size={17}/> Prywatność</span><span><SlidersHorizontal size={17}/> Kontrola</span><span><Sun size={17}/> Ciepło</span><span><Snowflake size={17}/> Zimno</span></div></div>
 <section className="section catalog-section" id="oferta"><div className="section-heading"><div><p className="eyebrow">01 / ROLETY, MOSKITIERY I ŻALUZJE</p><h2>Dobrze być<br/><span>po swojej stronie.</span></h2></div><p className="section-intro">Światło, cisza i odrobina prywatności.<br/>Zacznij od rozwiązań, które każdego dnia<br className="desktop-break"/> robią różnicę.</p></div><div className="product-grid">{products.filter(p=>p.group==='outside').map((p,i)=>card(p,'0'+(i+1)))}</div><div className="catalog-lists">{[{title:'Rolety wewnętrzne',sub:'Światło na Twoich zasadach',group:'inside'},{title:'Moskitiery',sub:'Więcej powietrza, mniej owadów',group:'insect'},{title:'Żaluzje',sub:'Precyzja w każdym promieniu',group:'blind'}].map(col=><div className="catalog-column" key={col.group}><div className="catalog-column-heading"><h3>{col.title}</h3><p>{col.sub}</p></div>{products.filter(p=>p.group===col.group).map(p=><a className="catalog-row" href={'/produkty/'+p.slug} key={p.slug}><span>{p.name}</span><ArrowUpRight size={17}/></a>)}</div>)}</div></section>
 <section className="section architecture-section" id="architektura"><div className="section-heading"><div><p className="eyebrow">01+ / BRAMY, PERGOLE I KRATY</p><h2>Twój dom.<br/><span>Szersza perspektywa.</span></h2></div><p className="section-intro">Od pierwszego wjazdu po ostatni<br/>promień słońca na tarasie.<br/>Zadbaj o całą przestrzeń wokół siebie.</p></div><div className="product-grid architecture-grid">{['brama-segmentowa','pergola','brama-garazowa'].map((slug,i)=>card(products.find(p=>p.slug===slug)!,'0'+(i+1)))}</div><div className="architecture-bottom">{products.filter(p=>['industrial',undefined].includes(p.model)&&p.group==='architecture').map(p=><article key={p.slug}><img src={'/images/original-'+p.image+'.jpeg'} alt={p.name} loading="lazy"/><div><span className="small-label">DLA TWOJEGO BIZNESU</span><a href={'/produkty/'+p.slug}><h3>{p.name}<ArrowUpRight size={19}/></h3></a><p>{p.lead}</p>{p.model&&<button className="model-trigger" onClick={()=>setModel(p.model!)}><Box size={15}/> Zobacz konstrukcję 3D</button>}</div></article>)}</div></section>
 <section className="section lab-section" id="laboratorium"><div className="lab-heading"><div><p className="eyebrow">LAB 01 / STREFA INTERAKCJI</p><h2>Brama ma<br/><span>swój rytm.</span></h2></div><div><span className="lab-tag">TRYPTYK GIER</span><p className="section-intro">Trzy sposoby, żeby poznać automatykę bliżej:<br/>zręczność, montaż i świadome decyzje.<br/>Każda gra ładuje się dopiero na żądanie.</p></div></div><div className="game-switcher" role="group" aria-label="Wybór ćwiczenia">{games.map(g=><button key={g.id} type="button" className={'game-switch'+(game===g.id?' game-switch-active':'')} aria-pressed={game===g.id} onClick={()=>setGame(g.id)}><span>{g.num}</span>{g.title}</button>)}</div><article className="game-chapter"><div className="game-chapter-heading"><span className="small-label">{activeGame.num} / {activeGame.tag}</span><h3>{activeGame.title}</h3><p>{activeGame.desc}</p></div><GameSlot key={game} game={activeGame.id} label={activeGame.label}/></article></section>
 <section className="section studio-section" id="studio"><div className="section-heading"><div><p className="eyebrow">02 / TWOJE STUDIO 3D</p><h2>Nie tylko zobacz.<br/><em>Poczuj różnicę.</em></h2></div><p className="section-intro">Zmieniaj kolory. Odkrywaj konstrukcję.<br/>Przymierz rozwiązanie do swojego domu.<br/>Wszystko zaczyna się od Twojego pomysłu.</p></div><Studio webmcp/></section>
 <section className="section gallery-section" id="realizacje"><div className="section-heading"><div><p className="eyebrow">03 / REALIZACJE ARTAS</p><h2>Najlepiej wyglądamy<br/><span>w rzeczywistości.</span></h2></div><p className="section-intro">Domy i miejsca pracy.<br/>Różne potrzeby, ten sam szacunek do detalu.</p></div><div className="gallery-grid">{gallery.slice(0,showAll?gallery.length:6).map((g,i)=><button key={g.i} className={'gallery-item gallery-item-'+i} onClick={()=>setPhoto(i)} aria-label={'Powiększ zdjęcie: '+g.title}><img src={'/images/original-'+g.i+'.jpeg'} alt={g.title} loading="lazy"/><div className="gallery-caption"><span>{g.cat}<b>{g.title}</b></span><Plus size={23}/></div></button>)}</div><div className="gallery-more"><span>Detale z naszych realizacji</span><button className="outline-btn" onClick={()=>setShowAll(!showAll)}>{showAll?'Pokaż mniej':'Więcej realizacji'}{showAll?<Minus size={15}/>:<Plus size={15}/>}</button></div></section>
 <section className="section process-section" id="wspolpraca"><div className="section-heading"><div><p className="eyebrow">04 / OD POMYSŁU DO CODZIENNOŚCI</p><h2>Dobry efekt<br/><span>ma dobry początek.</span></h2></div><a className="text-link" href="#kontakt">Porozmawiajmy o szczegółach <ArrowUpRight size={20}/></a></div><div className="process-grid">{[['01','Rozmowa','Opowiedz nam o swoim domu i tym, co chcesz zmienić.'],['02','Pomiar i dobór','Sprawdzamy wymiary, warunki montażu i wybieramy odpowiedni system.'],['03','Montaż','Dbamy o osadzenie, regulację i poprawną pracę całego rozwiązania.'],['04','Komfort na co dzień','Pokazujemy obsługę i podpowiadamy, jak dbać o osłony i automatykę.']].map(([n,t,d])=><article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div><div className="automation-strip"><div><span className="small-label">AUTOMATYKA, CZĘŚCI I AKCESORIA</span><h3>Cały dom. W jednym rytmie.</h3></div><div><a href="mailto:artasrolety@gmail.com?subject=Automatyka%20i%20SmartHome"><Radio size={21}/>Automatyka i SmartHome<ArrowUpRight size={15}/></a><a href="mailto:artasrolety@gmail.com?subject=Cz%C4%99%C5%9Bci%20do%20rolet%20i%20bram"><Settings2 size={21}/>Części do rolet i bram<ArrowUpRight size={15}/></a><a href="mailto:artasrolety@gmail.com?subject=Akcesoria"><Wrench size={21}/>Akcesoria<ArrowUpRight size={15}/></a></div></div></section>
 <Footer/><ModelDialog kind={model} onClose={()=>setModel(null)}/><Dialog open={photo!==null} onOpenChange={v=>{if(!v)setPhoto(null)}}><DialogContent className="gallery-dialog" showCloseButton={false}>{photo!==null&&<><div className="gallery-dialog-heading"><div><DialogTitle>{gallery[photo].title}</DialogTitle><DialogDescription>Realizacja ARTAS · {photo+1} / {gallery.length}</DialogDescription></div><DialogClose className="icon-button" aria-label="Zamknij zdjęcie"><X size={23}/></DialogClose></div><img src={'/images/original-'+gallery[photo].i+'.jpeg'} alt={gallery[photo].title}/><div className="gallery-navigation"><button className="outline-btn" onClick={()=>setPhoto((photo+gallery.length-1)%gallery.length)}><ChevronLeft size={16}/>Poprzednie</button><button className="outline-btn" onClick={()=>setPhoto((photo+1)%gallery.length)}>Następne<ChevronRight size={16}/></button></div></>}</DialogContent></Dialog></main>
}
