export type ModelKind = 'roller'|'flush'|'top'|'gate'|'industrial'|'rolling-gate'|'commercial-grille'|'pergola';
export type Product = {slug:string; name:string; group:'outside'|'inside'|'insect'|'blind'|'architecture'; lead:string; description:string; features:string[]; image?:number; model?:ModelKind; detail:string};
export const products:Product[]=[
 {slug:'moskitiera',name:'Moskitiera',group:'insect',lead:'Świeże powietrze. Bez nieproszonych gości.',description:'Dopasowana do okna siatka zatrzymuje owady i pozwala swobodnie wietrzyć pomieszczenia. Delikatna rama wtapia się w stolarkę, a całość można zdemontować do sezonowego czyszczenia.',features:['Rama na wymiar','Swobodna cyrkulacja powietrza','Wygodne czyszczenie'],detail:'Dobór ramki, sposobu mocowania i siatki zależy od profilu okna. Podczas pomiaru sprawdzamy miejsce na ramę oraz możliwość otwierania i zamykania skrzydła.'},
 {slug:'moskitiera-rolowana-balkonowa',name:'Moskitiera rolowana balkonowa',group:'insect',lead:'Otwarty balkon. Spokojne wieczory.',description:'Siatka zwija się do kasety, kiedy jej nie potrzebujesz. Prowadnice utrzymują ją przy otworze balkonowym, a dobrany do systemu mechanizm pozwala wygodnie zamknąć przejście.',features:['Siatka chowana w kasecie','Dopasowanie do drzwi balkonowych','Prowadzenie siatki'],detail:'Wybór kierunku zwijania i sposobu ryglowania ustalamy na podstawie wymiarów przejścia. Sprawdzamy też miejsce na kasetę, próg oraz kolizje z klamką.'},
 {slug:'roleta-natynkowa',name:'Roleta natynkowa',group:'outside',lead:'Duża zmiana. Bez dużego remontu.',description:'Skrzynka montowana na elewacji lub we wnęce okiennej mieści wał i zwinięty pancerz. To rozwiązanie pozwala dodać osłonę zewnętrzną do istniejącego domu.',features:['System adaptacyjny','Aluminiowy pancerz','Sterowanie ręczne lub napęd'],image:1,model:'roller',detail:'Model edukacyjny pokazuje skrzynkę, wał nawojowy, napęd rurowy, pancerz, prowadnice i listwę dolną. Profile 39, 43 i 52 mm są przykładami z katalogu Aluprof; ich dopuszczalne gabaryty zależą od wybranego systemu i warunków montażu.'},
 {slug:'roleta-podtynkowa',name:'Roleta podtynkowa',group:'outside',lead:'Technologia ukryta w architekturze.',description:'Skrzynka jest zintegrowana z warstwą elewacji nad oknem. Po wykończeniu budynku na pierwszy plan wysuwa się czysta forma okna i pancerza, a dostęp serwisowy pozostaje od spodu.',features:['Zabudowa w elewacji','Rewizja od dołu','Do zaplanowania z ociepleniem'],image:2,model:'flush',detail:'Inspiracją modelu jest układ Aluprof SP / SP-E. Sposób osadzenia, przestrzeń na skrzynkę i ciągłość izolacji należy uzgodnić przed wykonaniem elewacji. Wizualizacja nie wyznacza parametrów cieplnych ani wymiarów montażowych.'},
 {slug:'roleta-nadstawna',name:'Roleta nadstawna',group:'outside',lead:'Okno i roleta. Jedna przemyślana całość.',description:'Skrzynka łączy się z górną częścią ramy okiennej poprzez profil adaptacyjny. Zestaw osadza się razem z oknem, dlatego rozwiązanie warto uwzględnić przy budowie lub wymianie stolarki.',features:['Montaż razem z oknem','Izolowana skrzynka','Integracja z ramą'],image:3,model:'top',detail:'Układ oparto na zasadzie systemu SKT OPOTERM: skrzynka nad ramą, izolacja i dolny dostęp serwisowy zależny od wariantu. Konkretna kombinacja ramy, adaptera i wymiarów wymaga doboru systemowego.'},
 {slug:'roleta-dachowa',name:'Roleta dachowa',group:'inside',lead:'Światło pod kontrolą. Również na poddaszu.',description:'Osłona prowadzona przy skośnym oknie pomaga regulować światło w sypialni lub pokoju na poddaszu. Tkaninę oraz poziom zaciemnienia dobieramy do sposobu korzystania z pomieszczenia.',features:['Do okien połaciowych','Prowadzenie przy szybie','Dobór stopnia zaciemnienia'],detail:'Ta karta dotyczy wewnętrznej rolety do okna dachowego. Przed doborem sprawdzamy markę, model i oznaczenie rozmiaru na tabliczce okna. Zewnętrzna osłona dachowa jest odrębnym systemem — zapytaj nas o kompatybilność.'},
 {slug:'roleta-materialowa',name:'Roleta materiałowa',group:'inside',lead:'Wnętrze w Twoim odcieniu.',description:'Gładka tkanina porządkuje światło i staje się dyskretnym elementem wnętrza. Wariant wolnowiszący lub kasetowy dobieramy do okna i oczekiwanego efektu.',features:['Tkaniny transparentne i zaciemniające','Wersja w kasecie lub wolnowisząca','Kolor dopasowany do wnętrza'],detail:'Przepuszczalność światła zależy od tkaniny. Pełna ciemność w pomieszczeniu zależy także od sposobu montażu, prowadnic i szczelin przy krawędziach.'},
 {slug:'rolety-plisowane',name:'Rolety plisowane',group:'inside',lead:'Zasłoń dokładnie tyle, ile chcesz.',description:'Harmonijkowa tkanina pozwala osłonić wybraną część szyby. Możliwość ustawienia od dołu i od góry ułatwia pogodzenie prywatności z dostępem dziennego światła.',features:['Regulacja góra–dół','Dopasowanie do kształtu okna','Duży wybór tkanin'],detail:'Przy doborze sprawdzamy geometrię listwy przyszybowej, odległość od szyby i miejsce na uchwyty. Dostępność nietypowych kształtów zależy od wybranego systemu.'},
 {slug:'rolety-dzien-noc',name:'Rolety dzień–noc',group:'inside',lead:'Światło ma więcej niż dwa ustawienia.',description:'Naprzemienne pasy przejrzystej i gęstej tkaniny przesuwają się względem siebie. Zmieniasz dopływ światła bez konieczności całkowitego podnoszenia rolety.',features:['Płynna regulacja pasów','Wariant kasetowy','Prywatność i dzienne światło'],detail:'Efekt zaciemnienia zależy od wybranej tkaniny. Podświetlone wieczorem wnętrze może pozostawać częściowo widoczne, dlatego dobierzemy materiał do konkretnego pomieszczenia.'},
 {slug:'zaluzje-drewniane',name:'Żaluzje drewniane',group:'blind',lead:'Naturalna faktura. Wyrazisty charakter.',description:'Drewniane lamele kierują światło i wnoszą do pomieszczenia ciepły, naturalny detal. Obrót lameli daje kontrolę nad prywatnością i kierunkiem promieni słonecznych.',features:['Naturalny rysunek drewna','Regulacja kąta lameli','Dopasowane drabinki i taśmy'],detail:'Odcienie i usłojenie mogą różnić się między próbkami. Przy większych przeszkleniach sprawdzamy ciężar osłony i wysokość pakietu po podniesieniu.'},
 {slug:'zaluzje-aluminiowe',name:'Żaluzje aluminiowe',group:'blind',lead:'Lekka forma. Precyzyjna kontrola.',description:'Smukłe lamele aluminiowe pozwalają skierować światło w głąb pomieszczenia lub osłonić je od zewnątrz. Bogata kolorystyka ułatwia dopasowanie do stolarki i wnętrza.',features:['Lekka konstrukcja','Regulacja nachylenia','Różne szerokości lameli'],detail:'Rozmiar lameli i system sterowania dobieramy do wymiaru okna, dostępnego miejsca oraz klamek. Żaluzje wewnętrzne nie są przeznaczone do montażu na zewnątrz.'},
 {slug:'zaluzje-fasadowe',name:'Żaluzje fasadowe',group:'blind',lead:'Zatrzymaj słońce przed szybą.',description:'Zewnętrzne lamele regulują nasłonecznienie i charakter fasady. Zmiana ich kąta pozwala zachować widok na otoczenie przy ograniczonym dopływie bezpośredniego światła.',features:['Osłona przed przeszkleniem','Regulacja kąta lameli','Możliwość automatyki pogodowej'],image:6,detail:'Kształt lameli, prowadzenie oraz dopuszczalny wiatr są właściwościami konkretnego systemu. Przed montażem sprawdzamy miejsce na pakiet i zalecenia dotyczące automatyki pogodowej.'},
 {slug:'brama-garazowa',name:'Brama garażowa rolowana',group:'architecture',lead:'Więcej miejsca pod sufitem.',description:'Pancerz bramy zwija się na wał w skrzynce nad otworem. Konstrukcja nie wymaga długich prowadnic pod sufitem i może ułatwić wykorzystanie przestrzeni garażu.',features:['Zwijanie do skrzynki','Boczne prowadnice','Napęd elektryczny'],image:4,model:'rolling-gate',detail:'Model ilustruje bramę rolowaną z profilem nominalnym 77 mm, znacznie wyższym od profili okiennych. Nośność, zabezpieczenie przed opadnięciem i dostępne gabaryty wymagają doboru pełnego systemu.'},
 {slug:'brama-segmentowa',name:'Brama segmentowa',group:'architecture',lead:'Wjazd, który pasuje do całości.',description:'Wysokie, izolowane panele podnoszą się po prowadnicach i chowają pod sufitem garażu. Wykończenie dopasujesz do okien, drzwi i architektury elewacji.',features:['Wysokie panele segmentowe','Izolowane wypełnienie','Ruch po prowadnicach pod sufitem'],image:5,model:'gate',detail:'W konfiguratorze zastosowano przykładowe rynkowe moduły 500, 555 i 610 mm oraz grubość 40 mm. To warianty spotykane w systemach producentów, a nie jedna uniwersalna norma. Model korzysta z pełnych paneli: pięć po 500 mm lub cztery po 555/610 mm. Jego wysokość zmienia się odpowiednio do 2500, 2220 lub 2440 mm; rzeczywisty podział dobiera producent.'},
 {slug:'brama-segmentowa-przemyslowa',name:'Brama segmentowa przemysłowa',group:'architecture',lead:'Gotowa na rytm Twojego biznesu.',description:'Segmentowa konstrukcja zamyka większe otwory w halach, warsztatach i magazynach. Prowadzenie dobiera się do nadproża, wysokości hali i sposobu pracy obiektu.',features:['Warianty prowadzenia','Możliwe przeszklenia paneli','Automatyka do zastosowań przemysłowych'],image:8,model:'industrial',detail:'Model pokazuje poglądowe prowadzenie standardowe i sekcję z oknami. Nie stanowi projektu dla konkretnej hali. Liczbę cykli, przeszklenia, napęd i zabezpieczenia ustalamy osobno dla każdego obiektu.'},
 {slug:'pergola',name:'Pergola',group:'architecture',lead:'Twój ulubiony pokój. Pod otwartym niebem.',description:'Aluminiowa konstrukcja z ruchomym dachem lamelowym tworzy osłoniętą przestrzeń na tarasie. Obracane lamele pozwalają regulować dostęp słońca i przewietrzanie.',features:['Ruchome lamele dachu','Odwodnienie w konstrukcji','Możliwość sterowania elektrycznego'],image:7,model:'pergola',detail:'Inspiracją konstrukcyjną jest Aluprof MB-OpenSky 140: słupy, obwodowe belki, lamele i mechanizm obrotu. Model pokazuje zakres 0–135°. Nazwa 140 nie oznacza wysokości lameli. Wymiary, obciążenia i sposób odwodnienia wymagają projektu producenta.'},
 {slug:'kraty-handlowe',name:'Kraty handlowe',group:'architecture',lead:'Ochrona, która zostawia przestrzeń na ekspozycję.',description:'Rolowana krata zabezpiecza otwór lokalu i pozwala zachować widoczność ekspozycji. Po otwarciu jej pancerz jest zwinięty nad wejściem.',features:['Widoczna ekspozycja','Kompaktowe zwijanie','Dobór do otworu handlowego'],image:9,model:'commercial-grille',detail:'Wzór i prześwit kraty, napęd oraz wymagana klasa odporności są dobierane do obiektu. Sam ażurowy wygląd nie określa poziomu zabezpieczenia przeciwwłamaniowego.'}
];
export const palette=[{name:'Antracyt',ral:'7016',hex:'#383e42'},{name:'Czarny',ral:'9005',hex:'#17191b'},{name:'Biały',ral:'9016',hex:'#ededeb'},{name:'Srebrny',ral:'9006',hex:'#a5a8a6'},{name:'Szare aluminium',ral:'9007',hex:'#777a78'},{name:'Grafit',ral:'7024',hex:'#4a4d52'},{name:'Bazalt',ral:'7012',hex:'#575d5e'},{name:'Szary',ral:'7035',hex:'#c6c9c3'},{name:'Kremowy',ral:'9001',hex:'#e7dfcd'},{name:'Brąz',ral:'8014',hex:'#4a382d'},{name:'Czekoladowy',ral:'8017',hex:'#45302b'},{name:'Czerwone wino',ral:'3005',hex:'#5e2028'},{name:'Zieleń',ral:'6005',hex:'#1c493a'},{name:'Granat',ral:'5011',hex:'#243342'},{name:'Złoty dąb',ral:'dekor',hex:'#ae773d'},{name:'Orzech',ral:'dekor',hex:'#65442f'}];
export const modelNames:Record<ModelKind,string>={roller:'Roleta natynkowa',flush:'Roleta podtynkowa',top:'Roleta nadstawna',gate:'Brama segmentowa',industrial:'Brama przemysłowa','rolling-gate':'Brama rolowana','commercial-grille':'Krata handlowa',pergola:'Pergola lamelowa'};
export const nominalProfiles=(kind:ModelKind)=>kind==='gate'||kind==='industrial'?[500,555,610]:kind==='rolling-gate'||kind==='commercial-grille'?[77]:kind==='pergola'?[]:[39,43,52];
export const assemblySteps:Record<'roller'|'gate',{id:string;name:string;hint:string}[]>={roller:[{id:'guides',name:'Prowadnice',hint:'Prowadnice wyznaczają tor pancerza.'},{id:'box',name:'Korpus skrzynki',hint:'Skrzynka łączy się z prowadnicami i mieści mechanizm.'},{id:'shaft',name:'Wał i napęd',hint:'Wał jest podparty wewnątrz skrzynki.'},{id:'curtain',name:'Pancerz i wieszaki',hint:'Pancerz łączy się z wałem i porusza w prowadnicach.'},{id:'bottom',name:'Listwa dolna',hint:'Listwa kończy pancerz i stabilizuje dolną krawędź.'},{id:'cover',name:'Pokrywa rewizyjna',hint:'Pokrywa zamyka skrzynkę z zachowaniem dostępu serwisowego.'}],gate:[{id:'guides',name:'Prowadnice pionowe',hint:'Prowadnice wyznaczają położenie płaszcza w otworze.'},{id:'tracks',name:'Łuki i tory poziome',hint:'Łuki łączą pionowe prowadzenie z częścią pod sufitem.'},{id:'curtain',name:'Panele, zawiasy i rolki',hint:'Połączone panele przemieszczają się w prowadnicach.'},{id:'shaft',name:'Zespół równoważący',hint:'Sprężyny i linki równoważą ciężar. To zamknięty moduł demonstracyjny — w rzeczywistości montuje go fachowiec.'},{id:'motor',name:'Szyna z napędem',hint:'Napęd połączony z górnym panelem steruje ruchem bramy.'},{id:'sensor',name:'Zabezpieczenia',hint:'Model uzupełniamy o czujniki. Rzeczywiste zabezpieczenia wymagają kontroli i odbioru.'}]};
